phrase:
  access_token: ef603dab77025557420e3cfcaeb840097ec21d9dfe007686faf9ffb69f5d3325
  project_id: a7523de3fdf7ceeabe1e69a7177e33e9
  push:
    sources:
    - file: ./resources/lang/en/messages.php
      params:
        file_format: laravel
        locale_id: en
  pull:
    targets:
    - file: ./resources/lang/fr/messages.php
      params:
        file_format: laravel
        locale_id: fr
